{% set name = "sqlite-anyio" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite_anyio-{{ version }}.tar.gz
  sha256: 9ecbcddf105e5862f7975a9827b684a19a987aad46f10699eadb22ea33bbd060

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - anyio >=4.0,<5.0

test:
  imports:
    - sqlite_anyio

about:
  home: https://github.com/davidbrochart/sqlite-anyio
  summary: Asynchronous client for SQLite using AnyIO
  keywords: sqlite, anyio
  dev_url: https://github.com/davidbrochart/sqlite-anyio
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
