{% set name = "sqlite-anyio" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite_anyio-{{ version }}.tar.gz
  sha256: 1d4c2f9e242cef88e1459cca6c7708b2a13b5a63147bd22340c16efd8ee5ffc2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - anyio >=4.0,<5.0

test:
  imports:
    - sqlite_anyio

about:
  home: https://github.com/davidbrochart/sqlite-anyio
  summary: Asynchronous client for SQLite using AnyIO
  keywords: sqlite, anyio
  dev_url: https://github.com/davidbrochart/sqlite-anyio
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
