{% set name = "sqlite-anyio" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlite_anyio-{{ version }}.tar.gz
  sha256: 12a8b0ececaa63d70d5cc5f91edbd932fc1eca9da70ebce2b31d3a199767b3d3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - anyio >=4.0,<5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - sqlite_anyio

about:
  home: https://github.com/davidbrochart/sqlite-anyio
  summary: Asynchronous client for SQLite using AnyIO
  keywords: sqlite, anyio
  dev_url: https://github.com/davidbrochart/sqlite-anyio
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
