schema_version: 1

context:
  name: sqlite-anyio
  version: 0.2.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlite_anyio-${{ version }}.tar.gz
  sha256: 7e1bb604f41da329f58e45fe76b6542816af3b199be0f667d00457e7d43a9c98

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - anyio >=4.0,<5.0

tests:
  - python:
      imports:
        - sqlite_anyio
  - requirements:
      run:
        - python ${{ python_min }}

about:
  summary: Asynchronous client for SQLite using AnyIO
  license_file: LICENSE
  license: MIT
  homepage: https://github.com/davidbrochart/sqlite-anyio
  repository: https://github.com/davidbrochart/sqlite-anyio

extra:
  recipe-maintainers:
    - davidbrochart
